forum/basic/messages/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns('basic.messages.views',
    url(r'(?P<mailbox>inbox|trash|sent)/$',
        view='message_list',
        name='messages'),

    url(r'compose(?:/(?P<content_type_id>\w+):(?P<object_id>\w+))?/$',
        view='message_create',
        name='create'),

    url(r'remove/(?P<object_id>\d+)/$',
        view='message_remove',
        name='remove'),

    url(r'(?P<object_id>\d+)/reply/$',
        view='message_reply',
        name='reply'),

    url(r'(?:(?P<mailbox>inbox|trash|sent)/)?(?P<object_id>\d+)/$',
        view='message_detail',
        name='message'),

    url(r'',
        view='message_list',
        name='messages'),
)

forum/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    # Examples:
    url(r'api/', include('forum_thread.urls')),
    url(r'^', 'forum_thread.views.index'),
)

forum/basic/messages/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.db.models import permalink, Manager, Q
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.generic import GenericForeignKey

FROM_STATUS_DRAFT = 0
FROM_STATUS_SENT = 1
FROM_STATUS_DELETED = 2

TO_STATUS_NEW = 0
TO_STATUS_READ = 1
TO_STATUS_REPLIED = 2
TO_STATUS_DELETED = 3


class MessageManager(Manager):
    """Returns messages according to message status"""

    def new(self, user):
        return self.filter(to_user=user, to_status=TO_STATUS_NEW)

    def sent(self, user):
        return self.filter(from_user=user, from_status=FROM_STATUS_SENT)

    def trash(self, user):
        return self.filter(Q(to_user=user, to_status=TO_STATUS_DELETED) |
            Q(from_user=user, from_status=FROM_STATUS_DELETED))

    def archive(self, user):
        return self.filter(to_user=user).exclude(to_status=TO_STATUS_DELETED)


class Message(models.Model):
    """ Message model """
    FROM_STATUS_CHOICES = (
        (FROM_STATUS_DRAFT, 'Draft'),
        (FROM_STATUS_SENT, 'Sent'),
        (FROM_STATUS_DELETED, 'Deleted')
    )
    TO_STATUS_CHOICES = (
        (TO_STATUS_NEW, 'New'),
        (TO_STATUS_READ, 'Read'),
        (TO_STATUS_REPLIED, 'Replied'),
        (TO_STATUS_DELETED, 'Deleted')
    )
    from_user = models.ForeignKey(User, related_name='sent_messages')
    to_user = models.ForeignKey(User, related_name='messages')
    from_status = models.PositiveSmallIntegerField(choices=FROM_STATUS_CHOICES, blank=True, null=True, default=1)
    to_status = models.PositiveSmallIntegerField(choices=TO_STATUS_CHOICES, blank=True, null=True, default=0)
    subject = models.CharField(blank=True, max_length=255)
    message = models.TextField(blank=True)
    created = models.DateTimeField(_('created'), auto_now_add=True)
    modified = models.DateTimeField(_('modified'), auto_now=True)
    objects = MessageManager()

    content_type = models.ForeignKey(ContentType, blank=True, null=True, related_name='messages')
    object_id = models.IntegerField(blank=True, null=True)
    object = GenericForeignKey()

    class Meta:
        verbose_name = _('message')
        verbose_name_plural = _('messages')
        db_table = 'messages'
        ordering = ('-id',)

    def __unicode__(self):
        return u'Message from %s' % self.from_user.username

    @permalink
    def get_absolute_url(self):
        return ('messages:message', None, {'object_id': self.pk})

    @property
    def is_new(self):
        if self.to_status == TO_STATUS_NEW:
            return True
        return False

    def save(self, *args, **kwargs):
        super(Message, self).save(*args, **kwargs)
        if not self.object:
            self.object = self
            self.save()

forum/basic/messages/forms.py
from django import forms
from django.contrib.auth.models import User

from basic.messages.models import Message


class MessageForm(forms.ModelForm):
    to_user = forms.CharField()

    class Meta:
        model = Message
        exclude = ('to_status', 'from_status', 'from_user', 'object_id', 'content_type')

    def clean_to_user(self):
        if self.cleaned_data['to_user']:
            try:
                user = User.objects.get(username=self.cleaned_data['to_user'])
                self.cleaned_data['to_user'] = user
                return self.cleaned_data['to_user']
            except User.DoesNotExist:
                pass
        raise forms.ValidationError(u'There are no users with this username.')

forum/basic/groups/views/messages.py
from django.shortcuts import get_object_or_404

from basic.groups.decorators import *
from basic.groups.models import *
from basic.groups.forms import *
from basic.tools.shortcuts import render, redirect


def message_list(request, slug, topic_id, template_name='groups/messages/message_list.html'):
    """
    Returns a group topic message list page.

    Templates: ``groups/messages/message_list.html``
    Context:
        group
            Group object
        topic
            GroupTopic object
        message_list
            List of GroupMessage objects
    """
    group = get_object_or_404(Group, slug=slug, is_active=True)
    topic = get_object_or_404(GroupTopic, pk=topic_id, group=group, is_active=True)
    return render(request, template_name, {
        'group': group,
        'topic': topic,
        'message_list': topic.messages.all()
    })


def message_detail(request, slug, topic_id, message_id,
        template_name='groups/messages/message_detail.html'):
    """
    Returns a message detail page.

    Templates: ``groups/messages/message_detail.html``
    Context:
        group
            Group object
        topic
            GroupTopic object
        message
            GroupMessage object
    """
    group = get_object_or_404(Group, slug=slug, is_active=True)
    topic = get_object_or_404(GroupTopic, pk=topic_id, is_active=True)
    message = get_object_or_404(GroupMessage, pk=message_id, is_active=True)
    return render(request, template_name, {
        'group': group,
        'topic': topic,
        'message': message
    })


@membership_required
def message_create(request, slug, topic_id,
        template_name='groups/messages/message_form.html'):
    """
    Returns a group message form.

    Templates: ``groups/messages/message_form.html``
    Context:
        group
            Group object
        topic
            GroupTopic object
        form
            GroupMessageForm object
    """
    group = get_object_or_404(Group, slug=slug)
    topic = get_object_or_404(GroupTopic, pk=topic_id, group=group)
    if request.method == 'POST':
        form = GroupMessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.user = request.user
            message.topic = topic
            message.save()
            return redirect(request, topic)
    else:
        form = GroupMessageForm()
    return render(request, template_name, {
        'group': group,
        'topic': topic,
        'form': form,
    })


@membership_required
def message_edit(request, slug, topic_id, message_id,
        template_name='groups/messages/message_form.html'):
    """
    Returns a group message edit form.

    Templates: ``groups/messages/message_form.html``
    Context:
        group
            Group object
        topic
            GroupTopic object
        message
            GroupMessage object
        form
            GroupMessageForm object
    """
    message = get_object_or_404(GroupMessage, pk=message_id, is_active=True)
    if request.method == 'POST':
        form = GroupMessageForm(request.POST, instance=message)
        if form.is_valid():
            form.save()
            return redirect(request, message.topic)
    else:
        form = GroupMessageForm(instance=message)
    return render(request, template_name, {
        'group': message.topic.group,
        'topic': message.topic,
        'message': message,
        'form': form,
    })


@membership_required
def message_remove(request, slug, topic_id, message_id,
        template_name='groups/messages/message_remove_confirm.html'):
    """
    Returns a message delete confirmation page.

    Templates: ``groups/messages/message_remove_confirm.html``
    Context:
        group
            Group object
        topic
            GroupTopic object
        message
            GroupMessage object
    """
    message = get_object_or_404(GroupMessage, pk=message_id, is_active=True)
    if request.method == 'POST':
        message.is_active = False
        message.save()
        return redirect(request, message.topic)
    return render(request, template_name, {
        'group': message.topic.group,
        'topic': message.topic,
        'message': message,
    })

forum/basic/messages/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.http import Http404, HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.contenttypes.models import ContentType

from basic.messages.models import Message, TO_STATUS_READ, TO_STATUS_DELETED, FROM_STATUS_DELETED
from basic.messages.forms import MessageForm
from basic.tools.baseconv import base62

@login_required
def message_list(request, mailbox=None, template_name='messages/message_list.html'):
    """
    Returns a list of user messages.

    Template:: ``messages/message_list.html``
    Context:
        message_list
            List of Message objects
        mailbox
            String representing the current 'mailbox'
    """
    message_list = _get_messages(request.user, mailbox)
    return render_to_response(template_name, {
        'message_list': message_list,
        'mailbox': mailbox or 'archive'
    }, context_instance=RequestContext(request))


@login_required
def message_create(request, content_type_id=None, object_id=None, 
                    template_name='messages/message_form.html'):
    """
    Handles a new message and displays a form.

    Template:: ``messages/message_form.html``
    Context:
        form
            MessageForm object
    """
    next = request.GET.get('next', None)
    if request.GET.get('to', None):
        to_user = get_object_or_404(User, username=request.GET['to'])
    else:
        to_user = None
    
    if content_type_id and object_id:
        content_type = ContentType.objects.get(pk=base62.to_decimal(content_type_id))
        Model = content_type.model_class()
        try:
            related_object = Model.objects.get(pk=base62.to_decimal(object_id))
        except ObjectDoesNotExist:
            raise Http404, "The object ID was invalid."
    else:
        related_object = None
    
    form = MessageForm(request.POST or None, initial={'to_user': to_user})
    if form.is_valid():
        message = form.save(commit=False)
        if related_object:
            message.object = related_object
        message.from_user = request.user
        message = form.save()
        return HttpResponseRedirect(next or reverse('messages:messages'))
    return render_to_response(template_name, {
        'form': form,
        'to_user': to_user,
        'related_object': related_object,
        'next': next,
    }, context_instance=RequestContext(request))


def message_reply(request, object_id, template_name='messages/message_form.html'):
    """
    Handles a reply to a specific message.
    """
    original_message = get_object_or_404(Message, pk=object_id)
    next = request.GET.get('next', None)
    initial = {
        'to_user': original_message.from_user,
        'subject': 'Re: %s' % original_message.subject
    }
    form = MessageForm(request.POST or None, initial=initial)
    if form.is_valid():
        message = form.save(commit=False)
        message.object = original_message.object
        message.from_user = request.user
        message = form.save()
        return HttpResponseRedirect(next or reverse('messages:messages'))
    return render_to_response(template_name, {
        'form': form,
        'message': original_message,
        'next': next,
    }, context_instance=RequestContext(request))


@login_required
def message_remove(request, object_id, template_name='messages/message_remove_confirm.html'):
    """
    Remove a message.
    """
    message = get_object_or_404(Message, pk=object_id)
    next = request.GET.get('next', None)
    if request.method == 'POST':
        if message.to_user == request.user:
            message.to_status = TO_STATUS_DELETED
        else:
            message.from_status = FROM_STATUS_DELETED
        message.save()
        return HttpResponseRedirect(next or reverse('messages:messages'))
    return render_to_response(template_name, {
        'message': message,
        'next': next,
    }, context_instance=RequestContext(request))


@login_required
def message_detail(request, object_id, mailbox=None, template_name='messages/message_detail.html'):
    """
    Return a message.
    """
    message = get_object_or_404(Message, pk=object_id)
    content_type = ContentType.objects.get_for_model(message)
    thread_list = Message.objects.filter(object_id=message.object.pk, content_type=content_type).order_by('id')
    message_list = _get_messages(request.user, mailbox)
    if message.to_user == request.user:
        message.to_status = TO_STATUS_READ
        message.save()
    return render_to_response(template_name, {
        'message': message,
        'thread_list': thread_list,
        'message_list': message_list,
    }, context_instance=RequestContext(request))


def _get_messages(user, mailbox):
    if mailbox == 'sent':
        return Message.objects.sent(user)
    elif mailbox == 'trash':
        return Message.objects.trash(user)
    else:
        return Message.objects.archive(user)

forum/basic/messages/templates/messages/base_messages.html
{% extends "base.html" %}


{% block title %}Messages{% endblock %}
{% block body_class %}messages{% endblock %}


{% block content_aside %}
  <h3>Messages</h3>
  <ul>
    <li><a href="{% url messages:messages mailbox="inbox" %}">Inbox</a></li>
    <li><a href="{% url messages:messages mailbox="sent" %}">Sent</a></li>
    <li><a href="{% url messages:messages %}">Archive</a></li>
    <li><a href="{% url messages:messages mailbox="trash" %}">Trash</a></li>
    <li><a href="{% url messages:create %}">Compose</a></li>
  </ul>
{% endblock %}

forum/basic/messages/templates/messages/message_detail.html
{% extends "messages/base_messages.html" %}


{% block title %}Message{% endblock %}
{% block body_class %}{{ block.super }} message_detail{% endblock %}


{% block content_title %}
  <h3>From: {{ message.from_user }}</h3>
  <h2>Subject: {{ message.subject }}</h2>
{% endblock %}


{% block content %}
  <div class="message_list">
    {% for thread_message in thread_list %}
      <div class="item{% if thread_message == message %} current{% endif %}">
        <h4>{{ thread_message.from_user }} <a href="{{ thread_message.get_absolute_url }}">{{ thread_message.subject|default:"No subject" }}</a> {{ thread_message.created|date }}</h4>
        <div class="body">
          {{ thread_message.message|linebreaks }}
          <p><a href="{% url messages:reply thread_message.pk %}">reply</a></p>
        </div>
      </div>
    {% empty %}
      <div class="item current">
        <h4>{{ message.from_user }} <a href="{{ message.get_absolute_url }}">{{ message.subject|default:"No subject" }}</a> {{ message.created|date }}</h4>
        <div class="body">
          {{ message.message|linebreaks }}
          <p><a href="{% url messages:reply message.pk %}">reply</a></p>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

forum/basic/messages/templates/messages/message_form.html
{% extends "messages/base_messages.html" %}


{% block title %}Compose message{% endblock %}
{% block body_class %}{{ block.super }} message_form{% endblock %}


{% block content_title %}
  <h2>{% if message %}Reply{% else %}Message composer{% endif %}</h2>
{% endblock %}


{% block content %}
  <form action="{% if message %}{% url messages:reply message.id %}{% else %}.{% endif %}{% if next %}?next={{ next }}{% endif %}" method="post">{% csrf_token %}
    {% if message %}
      {{ message.message|linebreaks }}
      <span style="display:none;">{{ form.to_user }}</span>
    {% else %}
      <p><label for="id_to_user">To</label> {{ form.to_user }}
        {% if form.to_user.errors %}<span class="errors">{{ form.to_user.errors|join:", " }}</span>{% endif %}</p>
    {% endif %}
    <p><label for="id_subject">Subject</label> {{ form.subject }}
      {% if form.subject.errors %}<span class="errors">{{ form.subject.errors|join:", " }}</span>{% endif %}</p>
    <p><label for="id_message">Message</label> {{ form.message }}
      {% if form.message.errors %}<span class="errors">{{ form.message.errors|join:", " }}</span>{% endif %}</p>
    <p class="submit">
      <button type="submit" name="submit" value="Send">Send</button>
      <a href="{% url messages:messages %}" class="cancel">Cancel</a>
    </p>
  </form>
{% endblock %}

forum/basic/messages/templates/messages/message_list.html
{% extends "messages/base_messages.html" %}


{% block title %}{{ mailbox|title }} messages{% endblock %}
{% block body_class %}{{ block.super }} message_list{% endblock %}


{% block content_title %}
  <h2>{{ mailbox|title }} messages</h2>
{% endblock %}


{% block content %}
  {% load messages %}

  <table>
    {% for message in message_list %}
    <tr{% if message.is_new and message.from_user != user %} class="new_message"{% endif %}>
      {% if message.to_user == user %}
        <td>{{ message.from_user }}</td>
      {% else %}
        <td>To: {{ message.to_user }}</td>
        <td>{{ message.get_from_status_display }}</td>
      {% endif %}
      <td><a href="{{ message.get_absolute_url }}">{{ message.subject|default:"No subject" }}</a></td>
      <td>{{ message.created|date }}</td>
      <td><a href="{% url messages:reply message.pk %}">reply</a></td>
    </tr>
    {% endfor %}
  </table>

  <p><a href="{% url messages:create %}" class="button">Compose message</a></p>
{% endblock %}

forum/basic/messages/templates/messages/message_remove_confirm.html
{% extends "messages/base_messages.html" %}


{% block title %}Remove message{% endblock %}
{% block body_class %}{{ block.super }} message_remove_confirm{% endblock %}


{% block content_title %}
  <h2>Remove message</h2>
{% endblock %}


{% block content %}
  {% load markup %}
  <form action=".{% if next %}?next={{ next }}{% endif %}" method="post">{% csrf_token %}
    <p>Are you sure you want to remove this message?</p>
    <p class="submit"><button type="submit">Indeed</button></p>
  </form>
{% endblock %}